version: "3.9"

services:
  stream_handler:
    build: ./streamer
    container_name: stream_handler
    command: [ "npm", "start" ]
    environment:
      - PORT=80
  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "80:80"
      - "1935:1935"
    depends_on:
      - stream_handler