version: "3.9"

services:
  stream_handler:
    build: ./streamer
    container_name: stream_handler
    environment:
      - PORT=80
    volumes:
      - recdir:/streamer_module/tmp/rec
  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "80:80"
      - "1935:1935"
    depends_on:
      - stream_handler
    volumes:
      - recdir:/tmp/rec

# Creates the volume
volumes:
  recdir: