version: "3"

services:
  stream-handler:
    build: ./streamer
    container_name: stream-handler
    # Image name is important so that we kompose can know which image to run for
    image: stream-handler
    ports:
      - "80"
    environment:
      - PORT=80
    volumes:
      - recdir:/streamer_module/tmp/rec
    labels:
      # Very important. Without this, it won't be able to pull local images
      kompose.image-pull-policy: "IfNotPresent"
  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "80:80"
      - "1935:1935"
    # Image name is important so that we kompose can know which image to run for
    image: nginxstream
    depends_on:
      - stream-handler
    volumes:
      - recdir:/tmp/rec
    labels:
      kompose.image-pull-policy: "IfNotPresent"

# Creates the volume
volumes:
  recdir: