# Containing configuration for the google key
version: "3.9"

services:
  stream_handler:
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/streamer_module/gkey.json
    volumes:
      - ${GOOGLE_APPLICATION_CREDENTIALS}:/streamer_module/gkey.json:ro