# Containing configuration for the google key
# Currently unused. We used this to inject the service account creds.
# Now we use kubernetes secret.
version: "3"

services:
  stream-handler:
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/streamer_module/gkey.json
    volumes:
      - ${GOOGLE_APPLICATION_CREDENTIALS}:/streamer_module/gkey.json:ro