apiVersion: v1
kind: Service
metadata:
  namespace: marc0-namespace
  name: backend-service
spec:
  ports:
    - name: "80"
      port: 80
      targetPort: 5000
  selector:
    service: backend
status:
  loadBalancer: {}
