apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: marc0-namespace
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      service: backend
      loadbalance: external
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        service: backend
        loadbalance: external
    spec:
      containers:
        - image: "us-central1-docker.pkg.dev/marc1robot/marc0-repo/backend:v1_4"
          imagePullPolicy: Always
          name: backend
          ports:
            - containerPort: 5000
          resources: {}
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /var/secrets/google/stream-key.json
          volumeMounts:
            - name: cred-key
              mountPath: /var/secrets/google
      restartPolicy: Always
      volumes:
        - name: cred-key
          secret:
            secretName: streamer-key
status: {}
