# The main ingress service for marc0. Responsible for routing all the things
# into the right services

# ! GKE ingress does not support other ports other than 80 and 443. Hence,
# ! We don't use this. To do this, use nginx instead
# https://cloud.google.com/community/tutorials/nginx-ingress-gke

# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: marc0-ingress
#   namespace: marc0-namespace
# spec:
#   defaultBackend:
#     service:
#       name: backend-service
#       port:
#         number: 80
#   rules:
#     # Redirect marc0 to the backend service
#     - host: marc0.jasoncoding.com
#       http:
#         paths:
#           - path: /
#             pathType: Prefix
#             backend:
#               service:
#                 name: backend-service
#                 port:
#                   number: 80
#           - path: /stream
#             pathType: Prefix
#             backend:
#               service:
#                 name: nginx
#                 port:
#                   number: 1935
