# The main ingress service for marc0. Responsible for routing all the things
# into the right services
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: marc0-ingress
  namespace: marc0-namespace
spec:
  defaultBackend:
    # TODO: Change into frontend
    service:
      name: frontend-service
      port:
        number: 80
  rules:
    # Redirect marc0 to the backend service
    - host: marc0.jasoncoding.com
      http:
        paths:
          - path: /*
            backend:
              service:
                name: backend-service
                port:
                  number: 80
          - path: /stream
            backend:
              service:
                name: nginx
                port:
                  number: 1935
