# Exposes nginx to have an external IP
apiVersion: v1
kind: Service
metadata:
  namespace: marc0-namespace
  name: nginx-external
spec:
  type: LoadBalancer
  selector:
    io.kompose.service: nginx
  ports:
    - name: rtmp
      port: 1935
      targetPort: 1935