apiVersion: v1
kind: Service
metadata:
  name: nginx-external
spec:
  type: LoadBalancer
  selector:
    io.kompose.service: nginx
  ports:
    - name: http
      port: 80
      targetPort: 80
    - name: rtmp
      port: 1935
      targetPort: 1935