# Autoscaler for nginx based on CPU util
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  labels:
      io.kompose.service: nginx
  namespace: marc0-namespace
  name: nginx
spec:
  maxReplicas: 4
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nginx
  targetCPUUtilizationPercentage: 85
