apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -o kubernetes/
    kompose.image-pull-policy: IfNotPresent
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: nginx
  name: nginx
spec:
  ports:
    - name: "80"
      port: 80
      targetPort: 80
    - name: "1935"
      port: 1935
      targetPort: 1935
  selector:
    io.kompose.service: nginx
# status:
#   loadBalancer: {}
