apiVersion: v1
kind: Service
metadata:
  namespace: marc0-namespace
  annotations:
    kompose.cmd: kompose convert -o kubernetes/
    kompose.image-pull-policy: IfNotPresent
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: stream-handler
  name: stream-handler
spec:
  ports:
    - name: "80"
      port: 80
      targetPort: 80
  selector:
    io.kompose.service: stream-handler
status:
  loadBalancer: {}
